"""
        THIS FILE CONTAINS CERTAIN CONSTANT VALUES RELATED TO CONNECTION WITH MONGODB
"""

HOST_NAME = '172.28.128.3'
PORT_NUMBER = 27017
DATABASE_NAME = 'collegeTemp'
COLLECTION_NAME = 'collegeData'

CONNECTION_ATTEMPT_DURATION_MS = 4000

